"""initial schema

Revision ID: 60a8a67090c8
Revises: 
Create Date: 2026-03-05 14:39:40.812162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a8a67090c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_country'), 'holidays', ['country'], unique=False)
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('sales_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sales_teams_id'), 'sales_teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'analyst', 'sales_team', name='userrole'), nullable=False),
    sa.Column('sales_team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sales_team_id'], ['sales_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('sales_team_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('pdate', sa.String(length=20), nullable=True),
    sa.Column('irr_target', sa.Float(), nullable=True),
    sa.Column('input_file_path', sa.String(length=500), nullable=True),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('run_weekday', sa.Integer(), nullable=True),
    sa.Column('run_weekday_name', sa.String(length=20), nullable=True),
    sa.Column('total_loans', sa.Integer(), nullable=True),
    sa.Column('total_balance', sa.Float(), nullable=True),
    sa.Column('exceptions_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('last_phase', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_team_id'], ['sales_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_run_id'), 'pipeline_runs', ['run_id'], unique=True)
    op.create_table('loan_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seller_loan_number', sa.String(length=100), nullable=False),
    sa.Column('exception_type', sa.String(length=100), nullable=False),
    sa.Column('exception_category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rejection_criteria', sa.String(length=120), nullable=True),
    sa.Column('loan_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_exceptions_id'), 'loan_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_loan_exceptions_seller_loan_number'), 'loan_exceptions', ['seller_loan_number'], unique=False)
    op.create_table('loan_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seller_loan_number', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('loan_program', sa.String(length=255), nullable=True),
    sa.Column('application_type', sa.String(length=100), nullable=True),
    sa.Column('orig_balance', sa.Float(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('lender_price_pct', sa.Float(), nullable=True),
    sa.Column('fico_borrower', sa.Integer(), nullable=True),
    sa.Column('dti', sa.Float(), nullable=True),
    sa.Column('pti', sa.Float(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('apr', sa.Float(), nullable=True),
    sa.Column('property_state', sa.String(length=10), nullable=True),
    sa.Column('purchase_price_check', sa.Boolean(), nullable=True),
    sa.Column('underwriting_pass', sa.Boolean(), nullable=True),
    sa.Column('comap_pass', sa.Boolean(), nullable=True),
    sa.Column('eligibility_pass', sa.Boolean(), nullable=True),
    sa.Column('disposition', sa.String(length=30), nullable=True),
    sa.Column('rejection_criteria', sa.String(length=120), nullable=True),
    sa.Column('loan_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_facts_id'), 'loan_facts', ['id'], unique=False)
    op.create_index(op.f('ix_loan_facts_seller_loan_number'), 'loan_facts', ['seller_loan_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_facts_seller_loan_number'), table_name='loan_facts')
    op.drop_index(op.f('ix_loan_facts_id'), table_name='loan_facts')
    op.drop_table('loan_facts')
    op.drop_index(op.f('ix_loan_exceptions_seller_loan_number'), table_name='loan_exceptions')
    op.drop_index(op.f('ix_loan_exceptions_id'), table_name='loan_exceptions')
    op.drop_table('loan_exceptions')
    op.drop_index(op.f('ix_pipeline_runs_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_teams_id'), table_name='sales_teams')
    op.drop_table('sales_teams')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_country'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
